name: Benchmark

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark-compare-pr:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537 # master
        with:
          toolchain: "1.96" # Also defined in workspace Cargo.toml

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - uses: taiki-e/install-action@15449e3094499af05d8d964a1c884208e4b8b595 # v2.81.11
        with:
          tool: cargo-criterion # Also defined in scripts/benchmark.sh

      - name: Compare PR results with baseline
        uses: boa-dev/criterion-compare-action@adfd3a94634fe2041ce5613eb7df09d247555b87 # v3.2.4
        with:
          branchName: ${{ github.base_ref || github.ref_name }}
          benchName: "criterion_benches"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Run benchmarks on main and publish criterion output to GitHub Pages
  benchmark-publish-history:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537 # master
        with:
          toolchain: "1.96" # Also defined in workspace Cargo.toml

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - uses: taiki-e/install-action@15449e3094499af05d8d964a1c884208e4b8b595 # v2.81.11
        with:
          tool: cargo-criterion # Also defined in scripts/benchmark.sh

      - name: Run main benchmarks
        # Also in benchmark.yml
        run: |
          cargo bench --bench criterion_benches --color never
      - name: Publish Criterion HTML + JSON to gh-pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/criterion
          destination_dir: benchmark-history
          keep_files: true

      - name: Publish baseline JSON for PR comparison
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/criterion
          destination_dir: benchmark-data/latest
          keep_files: true
