name: Nightly

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 4 * * *" # Nightly, 4 AM UTC

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUST_SCOPE: --all-targets --all-features

jobs:
  nightly:
    name: Test Rust ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - "1.96" # Also defined in workspace Cargo.toml
          - beta
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          key: ${{ matrix.os }}-${{ matrix.toolchain }}

      - uses: taiki-e/install-action@b6ff580856c41316412a0b9b60540fbc6f8c82cc # v2.86.7
        with:
          tool: cargo-workspace-lints, cargo-nextest, cargo-llvm-cov # Also defined in scripts/lint-check.sh

      - name: Run doctests
        run: cargo test --doc

      - name: Run tests
        run: cargo llvm-cov nextest --workspace $RUST_SCOPE

      - name: Run tests (release)
        run: cargo llvm-cov nextest --release --workspace $RUST_SCOPE

      - name: Check formatting
        run: ./scripts/format-check.sh
        # No need to run on every OS
        if: matrix.os == 'ubuntu-latest'

      - name: Check lints
        run: ./scripts/lint-check.sh
        # No need to run on every OS
        if: matrix.os == 'ubuntu-latest'
