name: Nightly

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 4 * * *" # Nightly, 4 AM UTC

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always
  RUST_SCOPE: --all-targets --all-features

jobs:
  nightly:
    name: Test Rust ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - "1.98.1" # Also defined in workspace Cargo.toml
          - beta
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy, llvm-tools-preview

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          key: ${{ matrix.os }}-${{ matrix.toolchain }}

      - uses: taiki-e/install-action@3f74d7c16a4242f1c95561e98edc25d36adb4375 # v2.87.12
        with:
          tool: cargo-workspace-lints, cargo-nextest, cargo-llvm-cov

      - name: Run doctests
        run: cargo test --locked --workspace --all-features --doc

      - name: Run tests
        run: cargo llvm-cov nextest --locked --workspace $RUST_SCOPE

      - name: Run tests (release)
        run: cargo llvm-cov nextest --locked --release --workspace $RUST_SCOPE

      - name: Check formatting
        run: ./scripts/format-check.sh
        # No need to run on every OS
        if: matrix.os == 'ubuntu-latest'

      - name: Check lints
        run: ./scripts/lint-check.sh
        # No need to run on every OS
        if: matrix.os == 'ubuntu-latest'
