name: Check semantic versioning

on:
  pull_request:
    branches: [main]

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  semver-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@9bc92bc5598b4f3bec5d910d352094982cb0c3b9 # v1.92
        with:
          toolchain: 1.92 # Also defined in workspace Cargo.toml

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Check semver compatibility - template_lib
        continue-on-error: true
        uses: obi1kenobi/cargo-semver-checks-action@6b69fcf40e9b5fb17adeb57e4b6ecd020649a239 # v2.9
        with:
          package: template_lib
          baseline: origin/main

      - name: Check semver compatibility - template_bin
        continue-on-error: true
        uses: obi1kenobi/cargo-semver-checks-action@6b69fcf40e9b5fb17adeb57e4b6ecd020649a239 # v2.9
        with:
          package: template_bin
          baseline: origin/main
