name: Check semantic versioning

on:
  pull_request:
    branches: [main]

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  semver-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537 # master
        with:
          toolchain: "1.96" # Also defined in workspace Cargo.toml

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Check semver compatibility - template_lib
        continue-on-error: true
        uses: obi1kenobi/cargo-semver-checks-action@6b69fcf40e9b5fb17adeb57e4b6ecd020649a239 # v2.9
        with:
          package: template_lib
          baseline: origin/main

      - name: Check semver compatibility - template_bin
        continue-on-error: true
        uses: obi1kenobi/cargo-semver-checks-action@6b69fcf40e9b5fb17adeb57e4b6ecd020649a239 # v2.9
        with:
          package: template_bin
          baseline: origin/main
