name: Check unused dependencies

on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  unused-dependencies-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: true

      - uses: taiki-e/install-action@3f74d7c16a4242f1c95561e98edc25d36adb4375 # v2.87.12
        with:
          tool: cargo-machete@0.9.2 # Also defined in scripts/tools.txt

      - name: Find unused dependencies
        run: cargo machete
